 ### Create webhook event
# just a comment
# @env dev
@USER_ID=1
@BASE_URL=https://webhook.site/9a7ad0dc-dd55-4403-8817-50432786b871
@TITLE=hello

POST {{BASE_URL}}/posts
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
  "title": "{{TITLE}}",
  "userId": {{USER_ID}}
}

# @env dev
# @env auth

POST https://webhook.site/9a7ad0dc-dd55-4403-8817-50432786b871
Content-Type: text/xml; charset=utf-8
SOAPAction: "urn:HelloWorld"
X-Req-Source: req.nvim

<?xml version="1.0" encoding="UTF-8"?>
<soapenv:Envelope
	xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"
	xmlns:req="urn:req-nvim">
	<soapenv:Header/>
	<soapenv:Body>
		<req:HelloWorldRequest>
			<req:Message>hello from req.nvim</req:Message>
		</req:HelloWorldRequest>
	</soapenv:Body>
</soapenv:Envelope>
